import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,track,event,validateProject,History,locateStep,arrangementSteps,stepSeconds,stepTime,eventsAt,audibleTracks,PATTERNS} from '../dist/model.js';
import {drumPCM,AudioGraph,Transport,renderAudio} from '../dist/audio.js';
import {encodeWav,crc32,zip,packProject,unpackProject} from '../dist/files.js';

const buffer=(channels,rate=48000)=>({numberOfChannels:channels.length,length:channels[0].length,sampleRate:rate,getChannelData:i=>Float32Array.from(channels[i])});

test('starter sessions contain valid musical data and survive the project schema round-trip',()=>{for(const style of ['midnight','house','trap','blank']){const p=createProject(style),v=validateProject(JSON.parse(JSON.stringify(p)));assert.equal(v.title,p.title);assert.equal(v.bpm,p.bpm);assert.equal(v.tracks.length,8);assert.deepEqual(v.tracks,p.tracks);assert.equal(arrangementSteps(v),arrangementSteps(p));for(const pattern of PATTERNS)for(let s=0;s<v.patternLengths[pattern];s++)for(const hit of eventsAt(v,s,'pattern',pattern)){assert.ok(Number.isFinite(hit.duration)&&hit.duration>0);assert.ok(hit.offset>=0);}}});

test('song positions cross repeats and variable-length sections without losing steps',()=>{const p=createProject('blank');p.patternLengths.B=32;p.arrangement=[{pattern:'A',repeats:2},{pattern:'B',repeats:3}];assert.equal(arrangementSteps(p),128);assert.deepEqual(locateStep(p,31,'song'),{pattern:'A',step:15,clip:0});assert.deepEqual(locateStep(p,32,'song'),{pattern:'B',step:0,clip:1});assert.deepEqual(locateStep(p,127,'song'),{pattern:'B',step:31,clip:1});assert.equal(locateStep(p,128,'song'),null);});

test('swing preserves bar duration and all supported step times increase',()=>{for(const bpm of [40,92,142,240])for(const swing of [0,0.14,0.65]){const p={bpm,swing};assert.equal(stepTime(16,p),240/bpm);for(let i=0;i<2048;i++)assert.ok(stepTime(i+1,p)>stepTime(i,p));assert.equal(stepTime(1,p),stepSeconds(p)*(1+swing));}});

test('mute, solo, probability, microtiming, and ratchets agree for live and export event selection',()=>{const p=createProject('blank'),t=p.tracks[0],n=event(0);n.offset=.2;n.ratchet=4;n.length=2;t.patterns.A=[n];let hits=eventsAt(p,0);assert.equal(hits.length,4);assert.ok(Math.abs(hits[3].offset-.95*stepSeconds(p))<1e-12);assert.equal(hits[0].duration,stepSeconds(p)/2);n.chance=0;assert.equal(eventsAt(p,0).length,0);n.chance=1;t.mute=true;assert.equal(eventsAt(p,0).length,0);t.mute=false;p.tracks[1].solo=true;assert.equal(eventsAt(p,0).length,0);t.solo=true;assert.equal(eventsAt(p,0).length,4);assert.equal(eventsAt(p,0,'pattern','A',p.tracks[1].id).length,0);assert.deepEqual(eventsAt(p,0),eventsAt(p,0));assert.equal(audibleTracks(p).length,2);});

test('untrusted project input is bounded and identifiers cannot become markup',()=>{const p=createProject('blank');p.tracks[0].id='bad" onclick="alert(1)';p.tracks[0].patterns.A=[{...event(900,400,-4,-2),id:'bad><',ratchet:500,offset:-10}];p.bpm=Infinity;p.swing=Infinity;const clean=validateProject(p);assert.match(clean.tracks[0].id,/^[a-zA-Z0-9_-]+$/);const n=clean.tracks[0].patterns.A[0];assert.match(n.id,/^[a-zA-Z0-9_-]+$/);assert.equal(n.step,15);assert.equal(n.note,108);assert.equal(n.ratchet,4);assert.equal(n.offset,0);assert.equal(n.velocity,.01);assert.equal(n.length,.25);assert.equal(clean.bpm,92);assert.throws(()=>validateProject({...p,tracks:Array.from({length:17},()=>track('kick'))}));assert.throws(()=>validateProject({...p,arrangement:[]}));p.tracks[0].patterns.A=Array.from({length:513},()=>event(0));assert.throws(()=>validateProject(p));});

test('undo and redo preserve chords, mixer settings, and arrangement and clear alternate futures',()=>{const p=createProject(),h=new History(3);const before=JSON.stringify(p);h.push(p);p.tracks[6].patterns.A.splice(0,3);p.tracks[0].volume=-30;p.arrangement.reverse();const after=JSON.stringify(p);const undone=h.undo(p);assert.equal(JSON.stringify(undone),before);assert.equal(JSON.stringify(h.redo(undone)),after);h.push(p);assert.equal(h.future.length,0);});

test('all seven drum voices produce finite, bounded, non-silent PCM with a quiet release',()=>{for(const kind of ['kick','snare','hat','openhat','clap','rim','tom'])for(const rate of [44100,48000])for(const tune of [-24,0,24]){const pcm=drumPCM(kind,rate,tune);let peak=0,energy=0;for(const s of pcm){assert.ok(Number.isFinite(s));peak=Math.max(peak,Math.abs(s));energy+=s*s;}assert.ok(peak>.1&&peak<=1,kind);assert.ok(energy/pcm.length>.0001,kind);assert.ok(Math.abs(pcm.at(-1))<.001,kind);assert.equal(pcm[0],0);}});

test('stereo 24-bit WAV is correctly interleaved and preserves signed PCM',()=>{const r=encodeWav(buffer([[-1,0,1],[.5,-.5,0]]),{bits:24,dither:false}),v=new DataView(r.bytes.buffer);assert.equal(new TextDecoder().decode(r.bytes.slice(0,4)),'RIFF');assert.equal(v.getUint32(4,true),r.bytes.length-8);assert.equal(v.getUint16(22,true),2);assert.equal(v.getUint32(24,true),48000);assert.equal(v.getUint16(34,true),24);assert.equal(v.getUint32(40,true),18);function int24(at){let n=v.getUint8(at)|(v.getUint8(at+1)<<8)|(v.getUint8(at+2)<<16);if(n&0x800000)n-=0x1000000;return n;}assert.equal(int24(44),-8388608);assert.equal(int24(47),4194304);assert.equal(int24(50),0);assert.equal(int24(53),-4194304);assert.equal(int24(56),8388607);assert.equal(r.clipped,0);});

test('WAV exports report clipping, normalize to -1 dBFS, sanitize non-finite samples and handle silence',()=>{const b=buffer([[2,-2,NaN,Infinity],[0,0,0,0]],44100);assert.equal(encodeWav(b,{bits:16}).clipped,2);const r=encodeWav(b,{bits:16,normalize:true,dither:false});assert.equal(r.clipped,0);assert.equal(r.peak,2);const peak=new DataView(r.bytes.buffer).getInt16(44,true)/32767;assert.ok(Math.abs(20*Math.log10(peak)+1)<.002);const silent=encodeWav(buffer([[0,0],[0,0]]),{bits:24,normalize:true});assert.ok(silent.bytes.slice(44).every(n=>n===0));assert.throws(()=>encodeWav(buffer([[0]]),{bits:32}));});

test('ZIP stem archive uses correct CRC and directory offsets',async()=>{const data=new TextEncoder().encode('123456789');assert.equal(crc32(data),0xcbf43926);const blob=zip([{name:'01-Kick.wav',bytes:data},{name:'02-Snare.wav',bytes:new Uint8Array([1,2,3])}]);const raw=new Uint8Array(await blob.arrayBuffer()),v=new DataView(raw.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(14,true),0xcbf43926);const end=raw.length-22;assert.equal(v.getUint32(end,true),0x06054b50);assert.equal(v.getUint16(end+10,true),2);const central=v.getUint32(end+16,true);assert.equal(v.getUint32(central,true),0x02014b50);assert.equal(v.getUint32(central+42,true),0);});

test('portable project embeds only referenced samples and rejects missing or corrupt audio',async()=>{const p=createProject('blank');p.tracks[0].instrument='sample';p.tracks[0].sampleId='sample-1';const blob=new Blob([new Uint8Array([1,2,3,4])],{type:'audio/wav'});const samples=new Map([['sample-1',{name:'sample.wav',blob}],['unused',{name:'unused.wav',blob}]]);const packed=await packProject(p,samples);assert.equal(JSON.parse(packed).assets.length,1);let received;const decoded=await unpackProject(packed,{decodeAudioData:async b=>{received=new Uint8Array(b);return {duration:1,length:48000,numberOfChannels:1};}});assert.deepEqual(received,new Uint8Array([1,2,3,4]));assert.equal(decoded.samples.get('sample-1').name,'sample.wav');assert.equal(decoded.project.tracks[0].sampleId,'sample-1');await assert.rejects(()=>packProject(p,new Map()),/missing/);const raw=JSON.parse(packed);raw.assets=[];await assert.rejects(()=>unpackProject(JSON.stringify(raw),{}),/missing/);await assert.rejects(()=>unpackProject('{',{}));});

// An audio API contract double validates graph wiring and scheduling without a browser.
// Signal tests above exercise real generated PCM; this is not an audible browser test.
class Param {constructor(){this.value=0;this.events=[];}setValueAtTime(v,t){assert.ok(Number.isFinite(v)&&Number.isFinite(t)&&t>=0);this.events.push([v,t]);this.value=v;}linearRampToValueAtTime(v,t){this.setValueAtTime(v,t);}exponentialRampToValueAtTime(v,t){assert.ok(v>0);this.setValueAtTime(v,t);}setTargetAtTime(v,t){this.setValueAtTime(v,t);}cancelScheduledValues(){}cancelAndHoldAtTime(){}}
class Node {constructor(ctx,kind){this.ctx=ctx;this.kind=kind;this.connections=[];for(const n of ['gain','frequency','Q','pan','delayTime','threshold','knee','ratio','attack','release','playbackRate'])this[n]=new Param();}connect(n){this.connections.push(n);return n;}disconnect(){this.connections=[];}start(time,offset,duration){assert.ok(Number.isFinite(time)&&time>=0);if(offset!==undefined)assert.ok(offset>=0);if(duration!==undefined)assert.ok(duration>0);this.ctx.starts.push({time,kind:this.kind,offset,duration,source:this});}stop(time){assert.ok(time>=0);this.end=time;}getFloatTimeDomainData(data){data.fill(0);}}
class Context {constructor(ch=2,len=48000,rate=48000){this.sampleRate=rate;this.currentTime=0;this.state='running';this.length=len;this.nodes=[];this.starts=[];this.destination=new Node(this,'destination');}node(kind){const n=new Node(this,kind);this.nodes.push(n);return n;}createGain(){return this.node('gain');}createOscillator(){return this.node('oscillator');}createBufferSource(){return this.node('buffer-source');}createBiquadFilter(){return this.node('filter');}createStereoPanner(){return this.node('pan');}createAnalyser(){return this.node('analyser');}createDynamicsCompressor(){return this.node('compressor');}createConvolver(){return this.node('convolver');}createDelay(){return this.node('delay');}createBuffer(ch,len,rate){const data=Array.from({length:ch},()=>new Float32Array(len));return {numberOfChannels:ch,length:len,sampleRate:rate,duration:len/rate,getChannelData:i=>data[i],copyToChannel:(a,i)=>data[i].set(a)};}async resume(){}async startRendering(){return this.createBuffer(2,this.length,this.sampleRate);}}

test('audio graph wires every channel, updates mute/solo and releases sources',()=>{const p=createProject(),ctx=new Context(),g=new AudioGraph(ctx,p);assert.equal(g.channels.size,8);assert.ok(g.master.connections.includes(g.compressor));assert.ok(g.compressor.connections.includes(g.analyser));for(const c of g.channels.values()){assert.ok(c.meter.connections.includes(g.master));assert.ok(c.verb.connections.includes(g.reverb));assert.ok(c.echo.connections.includes(g.delay));}p.tracks[0].solo=true;g.update(p);assert.equal(g.channels.get(p.tracks[1].id).gain.value,undefined);assert.equal(g.channels.get(p.tracks[1].id).gain.gain.value,0);for(const t of p.tracks){const n=event(0,60);g.trigger(t,n,.1,.25);}assert.ok(ctx.starts.length>=8);g.stop();assert.equal(g.voices.size,0);assert.ok(ctx.starts.every(s=>s.source.end>=0));g.dispose();});

test('sampler applies original-pitch playback, trim offsets and reversed trim mapping',()=>{const p=createProject('blank'),t=p.tracks[0];t.instrument='sample';t.sampleId='s';t.trimStart=.2;t.trimEnd=.8;const ctx=new Context(),sample=ctx.createBuffer(2,48000,48000),g=new AudioGraph(ctx,p,new Map([['s',{buffer:sample}]]));g.trigger(t,event(0,72),.1,.15);let source=ctx.starts.at(-1);assert.equal(source.offset,.2);assert.equal(source.source.playbackRate.value,2);assert.ok(source.duration<=.6);t.reverse=true;t.trimStart=.1;t.trimEnd=.6;g.trigger(t,event(0,60),.5,.15);source=ctx.starts.at(-1);assert.equal(source.offset,.4);assert.notEqual(source.source.buffer,sample);g.dispose();});

test('transport schedules beyond UI timer ticks, repeats on the grid, and does not burst after a stall',async()=>{const p=createProject('blank');p.tracks[0].patterns.A=[event(0),event(4),event(8),event(12)];const ctx=new Context();let steps=[];const t=new Transport(()=>p,()=>new Map(),e=>steps.push(e));t.ctx=ctx;await t.start();clearInterval(t.timer);t.timer=null;assert.ok(t.graph.voices.size>0);for(let i=0;i<110;i++){ctx.currentTime=i*.025;t.tick();t.consume();}assert.ok(t.cycle>=1);assert.ok(steps.some(e=>e.absolute===15));const starts=ctx.starts.filter(s=>s.kind==='buffer-source');for(let i=1;i<starts.length;i++)assert.ok(Math.abs((starts[i].time-starts[i-1].time)-60/p.bpm)<1e-8);ctx.currentTime=120;t.tick();assert.ok(t.next<128);t.stop();assert.equal(t.playing,false);assert.equal(t.queue.length,0);});

test('offline exporter requests correct duration and excludes metronome',async()=>{let ctx;const Original=globalThis.OfflineAudioContext;globalThis.OfflineAudioContext=class extends Context{constructor(...args){super(...args);ctx=this;}};try{const p=createProject('blank');p.tracks[0].patterns.A=[event(0)];const result=await renderAudio(p,new Map(),{mode:'pattern',sampleRate:44100,tail:2});assert.equal(result.length,Math.ceil((16*stepSeconds(p)+2)*44100));assert.equal(ctx.starts.length,1);assert.equal(ctx.starts[0].time,0);assert.equal(ctx.starts[0].kind,'buffer-source');}finally{globalThis.OfflineAudioContext=Original;}});
